FROM gw000/keras:2.1.4-py3-tf-cpu

# install dependencies from python packages
RUN pip3 --no-cache-dir install \
    scikit-learn 

# install your app
ADD ./algo.py /
RUN chmod +x /algo.py

ENTRYPOINT ["python3", "/algo.py"]
