# Generated by Django 2.1.5 on 2019-02-08 21:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('building', 'Building'), ('training', 'Training'), ('complete', 'Complete'), ('aborted', 'Abordted'), ('failure', 'Failure')], default='created', help_text='Task status', max_length=16)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('started_on', models.DateTimeField(blank=True, null=True)),
                ('terminated_on', models.DateTimeField(blank=True, null=True)),
                ('failure_message', models.TextField(blank=True, help_text='Failure logs', null=True)),
                ('test_loss', models.DecimalField(decimal_places=6, help_text='Algorithm loss in percents.', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('test_accuracy', models.DecimalField(decimal_places=6, help_text='Algorithm loss in percents.', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('training_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.TrainingConfiguration')),
            ],
        ),
    ]
