# Generated by Django 2.1.5 on 2019-02-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_allow_null_on_task_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtask',
            name='docker_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
